//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spicy_management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SpicyEntities3 : DbContext
    {
        public DB_SpicyEntities3()
            : base("name=DB_SpicyEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Cat> TB_Cat { get; set; }
        public virtual DbSet<TB_Products> TB_Products { get; set; }
        public virtual DbSet<TB_Purchases> TB_Purchases { get; set; }
        public virtual DbSet<TB_Supplier> TB_Supplier { get; set; }
        public virtual DbSet<TB_users> TB_users { get; set; }
    }
}
