//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spicy_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cat
    {
        public int id { get; set; }
        public string CAT_Name { get; set; }
        public string CAT_Cover { get; set; }
    }
}
