//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spicy_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Products
    {
        public int id { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<int> product_code { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public string product_category { get; set; }
        public string product_supplier { get; set; }
    }
}
