//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spicy_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Purchases
    {
        public int id { get; set; }
        public string purchases_name { get; set; }
        public string purchases_supplier { get; set; }
        public Nullable<decimal> purchases_price { get; set; }
        public Nullable<int> purchases_quantity { get; set; }
    }
}
