//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spicy_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_users
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public Nullable<int> tax_value { get; set; }
    }
}
